---
apiVersion: hive.io/v1alpha1
kind: Cluster
metadata:
  name: gke-cluster
spec:
  provider: aws # (azure, gcp)
  version: 1.31
  region: us-east1 # provider specific
  vpc: "gke-vpc"
  # or
  # vpcRef: for externally created vpc
  control_plane:
    node_type: <machine_type> # (for provider)
    autoscale:
      min: 1
      max: 3
  cni: cilium # (flannel, calico)
  cluster_endpoint_public_access: true
